# config.py
ORACLE_USERNAME = "SYSTEM"
ORACLE_PASSWORD = "231801164"
ORACLE_DSN= "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=LAPTOP-2R8RL3VE)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)))"
# or replace with your DB connection string
